1:2.12~rc3+dfsg-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/qemu-make-debian-root b/debian/qemu-make-debian-root
--- a/debian/qemu-make-debian-root
+++ b/debian/qemu-make-debian-root
@@ -11,6 +11,14 @@ which debootstrap >/dev/null || {
     echo "error: missing debootstrap package" >&2
     exit 1
 }
+which sfdisk >/dev/null || {
+    echo "error: missing fdisk package" >&2
+    exit 1
+}
+which mke2fs >/dev/null || {
+    echo "error: missing e2fsprogs package" >&2
+    exit 1
+}
 
 KEEPFS=0
 SPARSE=0
